apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmaos-data
  namespace: gmaos
  labels:
    app.kubernetes.io/part-of: gmaos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: oci-bv
