apiVersion: v1
kind: Service
metadata:
  name: gmaos-runtime
  namespace: gmaos
  labels:
    app.kubernetes.io/name: gmaos-runtime
    app.kubernetes.io/part-of: gmaos
    app.kubernetes.io/component: runtime
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gmaos-runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
