apiVersion: v1
kind: Service
metadata:
  name: gmaos-web
  namespace: gmaos
  labels:
    app.kubernetes.io/name: gmaos-web
    app.kubernetes.io/part-of: gmaos
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gmaos-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
