import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import JSZip from 'jszip';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import type { EnterpriseItem } from './global-enterprise-orchestrator';

export interface PacketExport {
  itemId: string;
  title: string;
  docx: Buffer;
  pdf: Buffer;
  zip: Buffer;
}

export async function buildPacketExport(item: EnterpriseItem, packetType: 'capability' | 'grant' | 'closeout' = 'capability'): Promise<PacketExport> {
  const manifest = {
    itemId: item.itemId,
    title: item.title,
    lane: item.lane,
    priority: item.priority,
    packetType,
    generatedAt: new Date().toISOString(),
    source: item.source,
  };

  const docx = await buildDocx(item, packetType);
  const pdf = await buildPdf(item, packetType);
  const zip = await buildZip(item, packetType, docx, pdf, manifest);

  return {
    itemId: item.itemId,
    title: item.title,
    docx,
    pdf,
    zip,
  };
}

async function buildDocx(item: EnterpriseItem, packetType: string): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: item.title,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: `Packet type: ${packetType}` }),
          new Paragraph({ text: `Lane: ${item.lane}` }),
          new Paragraph({ text: `Priority: ${item.priority}` }),
          new Paragraph({ text: `Estimated value: $${item.estimatedValue.toFixed(2)}` }),
          new Paragraph({ text: '' }),
          new Paragraph({
            children: [new TextRun({ text: 'Summary', bold: true })],
          }),
          new Paragraph({ text: item.body }),
          new Paragraph({ text: '' }),
          new Paragraph({
            children: [new TextRun({ text: 'Approvals', bold: true })],
          }),
          new Paragraph({ text: 'This packet was generated by Already Here Global Enterprise ASIOS and is pending owner review before external use.' }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}

async function buildPdf(item: EnterpriseItem, packetType: string): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const page = pdfDoc.addPage();
  const { width, height } = page.getSize();
  let y = height - 50;

  function drawText(text: string, size: number, isBold = false): void {
    page.drawText(text, { x: 50, y, size, font: isBold ? boldFont : font });
    y -= size * 1.5;
  }

  drawText(item.title, 18, true);
  y -= 10;
  drawText(`Packet type: ${packetType}`, 12);
  drawText(`Lane: ${item.lane}`, 12);
  drawText(`Priority: ${item.priority}`, 12);
  drawText(`Estimated value: $${item.estimatedValue.toFixed(2)}`, 12);
  y -= 10;
  drawText('Summary', 14, true);

  const words = item.body.split(' ');
  let line = '';
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    const textWidth = font.widthOfTextAtSize(test, 12);
    if (textWidth > width - 100 && line) {
      drawText(line, 12);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) drawText(line, 12);

  y -= 10;
  drawText('Approvals', 14, true);
  drawText(
    'This packet was generated by Already Here Global Enterprise ASIOS and is pending owner review before external use.',
    12
  );

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
}

async function buildZip(
  item: EnterpriseItem,
  packetType: string,
  docx: Buffer,
  pdf: Buffer,
  manifest: Record<string, unknown>
): Promise<Buffer> {
  const zip = new JSZip();
  const folder = zip.folder(`${packetType}-${item.itemId}`);
  if (!folder) throw new Error('Failed to create zip folder');
  folder.file(`${packetType}.docx`, docx);
  folder.file(`${packetType}.pdf`, pdf);
  folder.file('manifest.json', JSON.stringify(manifest, null, 2));
  return zip.generateAsync({ type: 'nodebuffer' });
}
